name: 'Run PHPStan check via ReviewDog'
description: 'Run PHP Static Analyzer via ReviewDog.'
author: 'm0rff'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'

  level:
    description: 'Report level for reviewdog [info,warning,error].'
    default: 'warning'

  config_file:
    description: 'Configuration file (.neon) for phpstan.'
    default: 'phpstan.neon'

  reporter:
    description: 'Reporter of reviewdog command [github-pr-check,github-pr-review].'
    default: 'github-pr-check'

  fail_on_error:
    description: 'Fail on error.'
    default: 'false'

  args:
    description: 'Catch-all for any command-line arguments you would like to add.'
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_token }}
    - ${{ inputs.level }}
    - ${{ inputs.config_file }}
    - ${{ inputs.reporter }}
    - ${{ inputs.args }}
    - ${{ inputs.fail_on_error }}

branding:
  icon: 'check-circle'
  color: 'green'
